apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stockbot.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "stockbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        redeploy:  {{ .Values.deploytime | quote}}
      labels:
        app: {{ .Values.serviceName }}    
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
      nodeSelector:
        kubernetes.io/os: linux