apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace:  {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: {{ .Values.service.portname }}
  selector:
    app: {{ .Values.serviceName }}
