version: '3.7'

services:
  stockbot:
    image: hhh255533/stockbot:1.6.0
    pull_policy: always
    volumes:
      - log-data:/data/vault/logs

volumes:
  log-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/david/project/stockbot-logs'