

serviceName: 
namespace: 
replicaCount: 
deploytime: 

#image setting
image:
  repository: 
  pullPolicy: Always
  tag: ""

service:
  type: NodePort
  port: 80
  portname: http

# Deployment Setting
deployment:
  enabled: true
  resources:
    limits:
      cpu: 
      memory: 
    requests:
      cpu: 
      memory: 

ingress:
  enabled: false
