name: Deploy

on:
  workflow_dispatch:
    inputs:
      IMAGE_VERSION:
        description: "docker image version"
        required: true
        default: "1.0.0"
      OLD_VERSION:
        description: "docker image last version"
        required: true
        default: "1.0.0"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3

    - uses: microsoft/variable-substitution@v1 
      with:
          files: 'deploy/docker-compose.yaml'
      env:
          services.stockbot.image: ${{ secrets.DOCKERHUB_USERNAME }}/stockbot:${{ github.event.inputs.IMAGE_VERSION }}

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "deploy/docker-compose.yaml"
        target: "./project/stockbot"
        overwrite: true

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf ./project/stockbot/deploy/start.sh
          cat << EOF >> ./project/stockbot/deploy/start.sh
          docker-compose -f ./project/stockbot/deploy/docker-compose.yaml up -d
          echo "old version ${{ secrets.DOCKERHUB_USERNAME }}/stockbot:${{ github.event.inputs.OLD_VERSION }}
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/stockbot:${{ github.event.inputs.OLD_VERSION }}
          EOF

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          echo "${{ secrets.PASSWORD }}" | sudo -S sh ./project/stockbot/deploy/start.sh
          

